### ISSUE TITLE
Support the latest version of gensim

### ISSUE THREAD

**Issue by mykmal** [louisabraham/fastnode2vec#12]
The current version of fastnode2vec does not run with the latest version of gensim. When using gensim 4.0.1, attempting to run the fastnode2vec CLI returns the error message `TypeError:  __init__() got an unexpected keyword argument 'iter'`.

This error stems from the fact that gensim has renamed the `iter` parameter to `epochs` (see this [documentation page](https://radimrehurek.com/gensim/models/word2vec.html#gensim.models.word2vec.Word2Vec)). I am not sure if there are any other breaking changes.

**Comment by louisabraham** [comment]
Just pushed a potential fix, can you try? install with `pip install git+https://github.com/louisabraham/fastnode2vec`

**Comment by mykmal** [comment]
Thank you for working on this! The fix you pushed is necessary but not sufficient. Now I get the error message `TypeError: __init__() got an unexpected keyword argument 'size'`, and I confirmed that this is because the `size` parameter has been renamed to `vector_size` in gensim 4.0.

I found a comprehensive guide to migrating from gensim 3.x to gensim 4.0: https://github.com/RaRe-Technologies/gensim/wiki/Migrating-from-Gensim-3.x-to-4. Can you check whether any of the other changes listed there affect fastnode2vec?
