### ISSUE TITLE
ERROR while pip installing

### ISSUE THREAD

**Issue by sakshambassi** [louisabraham/fastnode2vec#13]
`pip install fastnode2vec` is failing with error message:

ERROR: Could not find a version that satisfies the requirement fastnode2vec

Is there some issue from pypi server side?

**Comment by louisabraham** [comment]
Are you using python3 ?

**Comment by sakshambassi** [comment]
Yes I am using Python 3

**Comment by louisabraham** [comment]
What version of Python 3 are you using?

**Comment by sakshambassi** [comment]
This was an issue due to incompatibility at our end of servers. Python version was 3.5.2. Closing the issue. Thanks!
