### ISSUE TITLE
pip install does not support latest gensim and networkx graph conversion to correct format

### ISSUE THREAD

**Issue by amjass12** [louisabraham/fastnode2vec#15]
Hi, 

I am trying to use this tool to run n2v on my graph networks. When I install fastnode2vec 0.0.5 from pypi, it seems gensim 4.0.1 is not supported (error below):

`TypeError: __init__() got an unexpected keyword argument 'iter'`

Secondly is it possible to convert an undirected networkx graph to the correct format as follows:

`graphn2v = Graph(nx_graph.edges(), directed=False, weighted=False)`

And finally, with regards to default parameters - is skip-gram the default model to use or does this need to be explicitly defined? Other node2vec tools allow for specifying the number of walks to carry out per node also, but it seems only walk length argument is available. Is there a way to also specify how many physical walks to take from each node?

thank you!

**Comment by louisabraham** [comment]
Your first error is fixed in the master branch, I'm going to deploy it now.

**Comment by louisabraham** [comment]
- You can pass any iterable describing the edges to `Graph`, with 2 values or 3 if the graph is weighted.

Thus, the following snippets work:

```py
import networkx as nx

# not weighted
nx_graph = nx.path_graph(3)
graph = Graph(nx_graph.edges, directed=False, weighted=False)

#weighted
nx_graph = nx.path_graph(3)
nx_graph.add_edge(2, 3, weight=5)
graph = Graph(nx_graph.edges.data("weight", default=1) , directed=False, weighted=True)
```

- skip-gram is always used, with the parameter `sg=1` being passed to  gensim

https://github.com/louisabraham/fastnode2vec/blob/bcf42b6434279bfe967f8baea0ce6aa81c865681/fastnode2vec/node2vec.py#L42-L49

- the number of walks to carry out per node is the `epochs` parameter

**Comment by amjass12** [comment]
thank you so much!
