### ISSUE TITLE
Corpus count and corpus word count incorrect

### ISSUE THREAD

**Issue by amjass12** [louisabraham/fastnode2vec#18]
Hi, 

I recently posted issue to #15 . This has all been fixed and works great (also unbelievable how fast this really is) ~2-3 mins for graph with 7000 nodes and 320k edges!

The code snippet I run is as follows (just to validate my understanding)

```
graph = Graph(nx_graph.edges, directed=False, weighted=False)
n2v = Node2Vec(graph, dim=100, walk_length=80, context=10, workers=12)

n2v.train(epochs=200)

```
is this code doing the following? 

- a walk of length 80
-  200 walks of length 80 from each node

I ask as, after training: if i run:

```
n2v.corpus_count
n2v.corpus_total_words
```
both = 7000 (number of nodes in graph)

this is incorrect - as the corpus count should be the total number of walks along all nodes (each sentence of 80) and the total words, should be the total number of words on all walks... is there a way of fixing this?

I should add. the embedding does work however, and results make sense - but it would be good just for validation of the walks and the corpus it creates. 

may i also confirm that the argument epochs in `n2v.train(epochs=200)` is the number of walks from each node and not the number of epochs sent to gensim Word2Vec (which is set to 1?) - is this also correct? if so is it possible to change the number of training epochs in w2v itself?

thank you!

**Comment by louisabraham** [comment]
Your understanding is right except for the number of words.

Nodes are translated to words and walks are translated to sentences / paragraphs.

https://stackoverflow.com/a/66821664

**Comment by louisabraham** [comment]
A corpus is synonym of dictionary and composed of unique words!

**Comment by louisabraham** [comment]
I don't think you should change the epochs yourself. Read the code and you will understand that the training is done by overwriting some precise methods of gensim to avoid storing walks: the walks are generated on the fly and passed to gensim.
The default epoch parameter would require me to pass a fixed training dataset on which gensim would loop.
My approach allows a near zero memory consumption apart from the graph and the embeddings and is independent of the number of walks or their size.

**Comment by amjass12** [comment]
thank you! will leave the training epochs alone!!  (the embedding is very accurate anyway, but just wanted to be completely clear!) - and also, the way it is being passed is super efficient ha!

with regards to the corpus count - I am still confused as the answer to the question starts with:

'total_words is the count of all raw words in the sentences in the corpus'

this would not be **unique** words but all words in total - so, this should show (in my example above) 7000 * 80 * 200 words

and the corpus count would be the length of number of sentences passed in .. 

What i am confused about is why it is showing 7000 nodes for `n2v.corpus_count` and `n2v.corpus_total_words` as this is not correct (unless it has something to do with the iterative passing of walks in to gensim)?

**Comment by louisabraham** [comment]
The corpus variables are initialized by the `build_vocab` function
https://github.com/louisabraham/fastnode2vec/blob/bcf42b6434279bfe967f8baea0ce6aa81c865681/fastnode2vec/node2vec.py#L50

I only give nodes, I don't need to generate any complete walks.

**Comment by amjass12** [comment]
@louisabraham thank you very much for clearing all of this up - this now makes sense!

As a complete aside, it might be useful to change the epochs parameter (as in number of walks) to something like 'num_walks', as it might be more intuitive. Thank you for building such a fast version of node2vec! :)
