### ISSUE TITLE
Context parameter in Node2Vec initialization

### ISSUE THREAD

**Issue by nicolasramirez0922** [louisabraham/fastnode2vec#23]
Hi! 

First of all thank you for the library!

I have a question. What does exactly the "context" parameter control in the initialization of Node2Vec?

I can not find it in current library code but it is necesary to initializate the class. It seems to affeect the computation time of training but I would like to know more.

Thanks!

**Comment by nicolasramirez0922** [comment]
I found a preview issue regarding this!

**Comment by louisabraham** [comment]
If you have time, a PR documenting parameters in the README would be much appreciated!
