### ISSUE TITLE
TypeError: gen_nodes() takes 0 positional arguments but 1 was given

### ISSUE THREAD

**Issue by mustfkeskin** [louisabraham/fastnode2vec#25]
def gen_nodes --> must be take epoch parameter

[This line function dont have any input](https://github.com/louisabraham/fastnode2vec/blob/2aa4a21a2cdd8b0c6fc2289af842c442cd08240d/fastnode2vec/node2vec.py#L129)

**Comment by louisabraham** [comment]
fixed
