### ISSUE TITLE
Do multiple instances of the same edge impact probability?

### ISSUE THREAD

**Issue by fratajcz** [louisabraham/fastnode2vec#26]
Hi!

First of all, great implementation, I use it for my research and it has saved me countless hours.

However, I was curious how multiple instances of the same edge are handled in this implementation. I went digging in the code a bit but couldnt find any clear indication.

Say we start at NodeA and the edgelist that I feed in has three edges outgoing from NodeA:

```
NodeA    NodeB
NodeA    NodeB
NodeA    NodeC
```

Is the walker now twice as likely to go to NodeB than to NodeC? 

Thanks for clarification!

**Comment by louisabraham** [comment]
Hi! The exact behavior would depend on [csr_matrix](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.csr_matrix.html)
If you want to be _sure_ about what will be done, you should put weights by using `weighted=True`.
