### ISSUE TITLE
How we can define number of random walks per root node?

### ISSUE THREAD

**Issue by mustfkeskin** [louisabraham/fastnode2vec#27]
[Node2vec slow edition](https://github.com/eliorc/node2vec)
We can define num_walks: Number of walks per node (default: 10)
How we can do it in this library

**Comment by louisabraham** [comment]
That would be epochs. I'm not sure how the other implem works but in ours, each epoch contains one random walk starting at each node.

**Comment by mustfkeskin** [comment]
https://github.com/pyg-team/pytorch_geometric/blob/master/examples/node2vec.py
This is pytorch implementation. For example, there are 100 epochs of training for pytorch and there are 10walks_per_node in each epoch. this feature can also be added to the repo
```
 model = Node2Vec(
        data.edge_index,
        embedding_dim=128,
        walk_length=20,
        context_size=10,
        walks_per_node=10,
        num_negative_samples=1,
        p=1,
        q=1,
        sparse=True,
    ).to(device)
```
Training loop
```
   for epoch in range(1, 101):
        loss = train()
        acc = test()
        print(f'Epoch: {epoch:03d}, Loss: {loss:.4f}, Acc: {acc:.4f}')
```

**Comment by louisabraham** [comment]
I don't understand what you mean
