### ISSUE TITLE
Is there a way to reproduce the same results every time with same parameter values?

### ISSUE THREAD

**Issue by karrtikiyer** [louisabraham/fastnode2vec#4]
If I run the node2vec with below parameters twice:
`n2v = Node2Vec(graph, dim=100, walk_length=100, context=5, p=1.0, q=0.6, workers=3)
n2v.train(epochs=100)`
`n2v_1 = Node2Vec(graph, dim=100, walk_length=100, context=5, p=1.0, q=0.6, workers=3)
n2v1.train(epochs=100)`
The results produce are different. I understand that this might be expected given walks are random. However I wanted to check if there is a way to reproduce the same results?  As of now I am saving these embeddings and then loading it whenever needed but wanted to check if there is a way to ensure reproducibility?
```
n2v.wv.most_similar('n55')
[('n27648', 0.6468332409858704),
 ('n78', 0.6370588541030884),
 ('n6906', 0.632738471031189),
 ('n6465', 0.6251925230026245),
 ('n3165', 0.6228950023651123),
 ('n6492', 0.6056016683578491),
 ('n27656', 0.6049143671989441),
 ('n85', 0.604266881942749),
 ('n5934', 0.6016391515731812),
 ('n27616', 0.5997741222381592)]
```
```
n2v_1.wv.most_similar('n55')
[('n78', 0.6871901154518127),
 ('n2495', 0.6181676387786865),
 ('n6192', 0.6168757677078247),
 ('n27648', 0.6100389957427979),
 ('n57', 0.6075147390365601),
 ('n6326', 0.606364369392395),
 ('n5934', 0.6040099859237671),
 ('n6465', 0.5965710878372192),
 ('n3165', 0.5962290167808533),
 ('n3400', 0.5955773591995239)]
```

**Comment by louisabraham** [comment]
Yes, one has to set the seed using  np.random.seed from numba code.

**Comment by karrtikiyer** [comment]
Ok, let me give that a try @louisabraham , I will submit a PR if that works as expected.
I had another question, do you have any thoughts around how to evaluate the embeddings generated say given right now I do not have a downstream prediction task with labelled data to optimise for?

**Comment by louisabraham** [comment]
Yes, you could do some link prediction :
- https://stellargraph.readthedocs.io/en/stable/demos/link-prediction/node2vec-link-prediction.html
- http://ceur-ws.org/Vol-2436/article_2.pdf
- https://github.com/adocherty/node2vec_linkprediction

Basically you randomly remove some edges from the graph and try to classify non-existent links vs removed links

**Comment by louisabraham** [comment]
About seed, I suggest to pass an optional integer parameter `seed` that is ignored if None.

**Comment by karrtikiyer** [comment]
Yes, I was planning to add `seed` as parameter. And was planning to set it in the function `generate_random_walk` in `graph.py`, does it make sense?

**Comment by louisabraham** [comment]
Totally!

**Comment by karrtikiyer** [comment]
I gave it a try, but given we are using numba, the random seed (`np.random.seed`) is not working as expected, if I take out the decorator `@njit(nogil=True)` from the `_random_walk` function then it works and results are reproducible. Any thoughts?

**Comment by louisabraham** [comment]
Can you please provide the code?

**Comment by louisabraham** [comment]
Note: you have to use 1 worker to get deterministic results.
