### ISSUE TITLE
Parameter for setting the number of walks per node

### ISSUE THREAD

**Issue by VHarisop** [louisabraham/fastnode2vec#6]
Thank you for your work on this!

In the original `node2vec` implementation, there is a `num_walks` parameter controlling the number of walks per source. Is there an easy way to control this in `fastnode2vec`?

**Comment by louisabraham** [comment]
Hi, this parameter is typically used to generate walks and store them, which causes huge memory consumption.
My implementation samples from the distribution of walks at each epoch
