### ISSUE TITLE
Sometimes there is an IndexError when generating random walk

### ISSUE THREAD

**Issue by fishstay** [louisabraham/fastnode2vec#9]
As title, when I run fastnode2vec, sometimes there raises an IndexError when generating random walk.  
However, if I run the same code again, there are three possible situations.

1. no mistakes
2. IndexError again
3. Segmentation Fault

Does anyone face the same problem or can anyone give me some suggestions?
I am not good at English. If there is something unclear, please let me know.
Thanks.

Here are the error messages:

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.7/site-packages/gensim/models/base_any2vec.py", line 210, in _worker_loop
    tally, raw_tally = self._do_train_job(data_iterable, job_parameters, thread_private_mem)
  File "/opt/conda/lib/python3.7/site-packages/fastnode2vec/node2vec.py", line 73, in _do_train_job
    sentences = [self.generate_random_walk(w[0]) for w in sentences]
  File "/opt/conda/lib/python3.7/site-packages/fastnode2vec/node2vec.py", line 73, in <listcomp>
    sentences = [self.generate_random_walk(w[0]) for w in sentences]
  File "/opt/conda/lib/python3.7/site-packages/fastnode2vec/node2vec.py", line 70, in generate_random_walk
    return self.graph.generate_random_walk(self.walk_length, self.p, self.q, t)
  File "/opt/conda/lib/python3.7/site-packages/fastnode2vec/graph.py", line 154, in generate_random_walk
    return self.node_names[walk].tolist()
IndexError: index 1493521 is out of bounds for axis 0 with size 136781
```

**Comment by louisabraham** [comment]
Hi, there must be a bug somewhere. Do you mind sharing the code that you use to generate the Graph and launch the training?

**Comment by fishstay** [comment]
Thanks for your quick reply. I'll try my best to illustrate my problem.
My raw data is a dataframe, which looks like the following example,

![image](https://user-images.githubusercontent.com/63065429/91579593-736e9700-e97e-11ea-81a1-8a0a1d6fc8ce.png)

The numbers in the first two columns represent products. It shows people's browsing history on my company's website. The weight shows how many times they look at the products. For example, the second row shows that people look at the product '2745463' and then look at the product '2711383' three times.

I first transfer the numbers in the first two columns to string.

`data.ref = data.ref.astype(int).astype(str)`
`data.to = data.to.astype(int).astype(str)`

Then, I  use the reciprocal of times as weight.

`data.weight = round(1/data.weight, 5)
`

Then, I transfer each row to a list of tuples, construct the graph, and train the model.

`graph_data = data.to_records(index = False).tolist()`
`graph = Graph(graph_data, directed = True, weighted = True)`
`n2v = Node2Vec(graph, dim = 50, walk_length = 15, context = 5, p = 2.0, q = 0.5, workers = 4)`
`n2v.train(epochs = 40)`

That's how I train the model. In the real case, I have about 136781 products. The training usually succeeds, but sometimes it raises IndexError. I cannot find the reason because the error doesn't appear every time.

**Comment by louisabraham** [comment]
So actually what is strange is that the error appears at the end of the generation, when replacing the node indices with their label. Hence the error comes from Graph.

Can you try:

```
graph.indices.max()
```


Btw, why do you invert weights? And why do you round them?

**Comment by louisabraham** [comment]
Can you show the 10 first elements of graph_data?

**Comment by fishstay** [comment]
The graph_data looks like

![未命名](https://user-images.githubusercontent.com/63065429/91590257-a79d8400-e98d-11ea-884b-e78fc5c18630.png)

I also doubt that the product numbers are mistaken for the node indices although they are strings.  Therefore, I come here to check whether there are some bugs. I'll try to check the indices. Thank you.

For me, the weight means the cost of the edge. If there are many people looking at the product '2745463' and then looking at the product '2711383', which means the cost from '2745463' to '2711383' is small. That is to say, the more times, the smaller cost. Therefore, I use the reciprocal of times as cost (weight). 

I round them because I find that it spends more time if the weights have more digits when training the model. Am I wrong?

**Comment by louisabraham** [comment]
I don't think your idea for weights is good. Node2vec is used to produce embeddings that reflect proximity in the data, and AFAIK no paper does what you describe . Another way why your cost seems strange is that if there is no edge (a,b), then you should give it weight infinite. I think you misunderstood the concept of similarity graph, thinking they are like distance graphs. If you need further explanation, I can provide you material!

Rounding as you do it just truncates in base 10 without changing the number of bits. Some people use 32 bit or even 16 bit floats but honestly it mostly saves memory and does not affect running time on modern CPU architectures (GPU and specialized hardware is another story).

Please give me the result of 

    graph.indices.max()

**Comment by fishstay** [comment]
The result of 
`graph.indices.max()`
is 136780, which is the number of nodes (products) - 1.

Please provide me some material about the similarity graph. Thank you for your help!

About the index error, I also find:
1493521 is not in the set of product numbers when encountering
 `IndexError: index 1493521 is out of bounds for axis 0 with size 136781`

**Comment by louisabraham** [comment]
> 1493521 is not in the set of product numbers when encountering
What do you mean?

This bug looks strange. Can you wrap the line with the bug in a try block and print the value of walk if the indexerror is raised? If you don't know how, I can create another branch tonight.

About material, maybe you can start with the paper itself https://arxiv.org/abs/1607.00653

**Comment by fishstay** [comment]
1493521 is not one of the nodes' labels. 

What do you mean about "the value of walk"? 

Fortunately, after I restart the kernel, I haven't met the IndexError today. Therefore, I cannot reproduce the error right now. I will try it when next time I face the same problem. Thank you.

**Comment by louisabraham** [comment]
I meant the value of the `walk` variable. Anyway, closing for now, don't hesitate to reopen if you can reproduce!
